services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: MaxDkn
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: musicdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://MaxDkn:test1234@db:5432/musicdb
    depends_on:
      - db

  ui:
    container_name: ui
    build: ./ui
    volumes:
      - ./ui:/app
    stdin_open: true
    tty: true
    depends_on:
      - api
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui
      - api


volumes:
  db_data:
